AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template that passes validation but fails during execution (SSM parameter with invalid tag keys)'

Parameters:
  Environment:
    Type: String
    Default: test

Resources:
  # SSM parameter with invalid tag keys - will pass validation but fail execution
  TestParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Environment}/execution-test/parameter-with-invalid-tags"
      Type: String
      Value: "This parameter will fail due to invalid tag keys"
      Description: "Parameter with invalid tag keys to test execution error handling"
      Tags:
        # Tag key with invalid characters ($ % ^ & * are not in the allowed pattern)
        "invalid$tag%key^with&forbidden*characters": "should-fail"
        # Tag key with brackets (not allowed)
        "tag[with]brackets": "should-fail"  
        # Tag key with pipes (not allowed)
        "tag|with|pipes": "should-fail"
        # Valid tag for comparison
        Environment: !Ref Environment

Outputs:
  ParameterName:
    Description: "Name of the parameter"
    Value: !Ref TestParameter
