AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template that passes validation but fails during execution (VPC and Subnet with overlapping CIDRs)'

Parameters:
  Environment:
    Type: String
    Default: test

Resources:
  # VPC with CIDR block
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-test-vpc"
        - Key: Environment
          Value: !Ref Environment

  # Subnet with CIDR that doesn't fit within VPC CIDR - will cause execution error
  TestSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TestVPC
      CidrBlock: 192.168.1.0/24  # This CIDR doesn't overlap with VPC CIDR 10.0.0.0/16
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-test-subnet"
        - Key: Environment
          Value: !Ref Environment

Outputs:
  VPCId:
    Description: "ID of the VPC"
    Value: !Ref TestVPC
  SubnetId:
    Description: "ID of the Subnet"
    Value: !Ref TestSubnet
