Parameters:
  Environment:
    Type: String
    AllowedValues:
      - beta
      - gamma
      - prod
    Default: beta
  AList:
    Type: CommaDelimitedList
Resources:
  SsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref Environment
  SsmParameterList:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Join [",", !Ref AList]
