Parameters:
  Environment:
    Type: String
    AllowedValues:
      - beta
      - gamma
      - prod
    Default: beta
Resources:
  SsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref Environment